name: Node.js CI

on:
  push:
    branches: [ test-feature06 , develop ]
  pull_request:
    branches: [ develop-feature06, develop, main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, debian, redhat]
        node-version: [16.x , 14.x]
    
    runs-on: self-hosted-${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install api dependencies
      working-directory: ./api
      run: |
        yarn global add jest
        yarn add @babel/runtime
        yarn && yarn seed
        echo "JWT_SECRET=test-jwt-secret" >> .env
        echo "ADMIN_JWT_SECRET=test-admin-jwt-secret" >> .env

    - name: Install client dependencies
      working-directory: ./client
      run: |
        yarn
    
    - name: Run unit tests
      working-directory: ./api
      run: yarn test:unit
    
    - name: Run integration tests
      working-directory: ./api
      run: yarn test:integration
